[package]
name = "tinker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"
env_logger = "0.11"
indicatif = "0.18"
log = "0.4"
rand = "0.9.2"
rayon = "1.10"

